# Databricks App entrypoint (app.yml required by deploy; see also app.yaml)
# https://docs.databricks.com/en/dev-tools/databricks-apps/app-runtime
command:
  - streamlit
  - run
  - app.py
  - --server.port=8000
  - --server.headless=true
  - --server.enableCORS=false
  - --browser.gatherUsageStats=false
